---
 - name: Make ansible adminstrator user
   hosts: "{{ HOSTS }}"
   gather_facts: false
   become: yes

   vars:
    sudo_file: "../teamplate/"
    ssh_pub_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
   
   pre_tasks:
    - name: Config ansible user
      user:
       name: "{{ user }}"
       shell: /bin/bash
       password_lock: yes
       comment: Ansible Administrator
       group: sudo

   tasks:
    - name: Copy sudoers nopasswd file
      template:
       src: "{{ sudo_file }}sudo.nopasswd.j2"
       dest: "/etc/sudoers.d/{{ user }}"
       owner: root
       group: root
       mode: '0440'

    - name: Add ssh public key
      authorized_key:
       user: "{{ user }}"
       state: present
       key: "{{ ssh_pub_key }}"