---
 - name: Default host config
   hosts: "{{ HOSTS }}"
   gather_facts: false
   become: yes
   
   tasks:

   - name: Cache update
     apt:
      update_cache: yes
      cache_valid_time: 3600
   
   - name: Install dependencies for apt work with https
     apt:
      pkg:
       - ca-certificates
       - curl
       - gnupg
       - lsb-release
      state: latest
   
   - name: Install latest aditional packeges
     apt:
      pkg:
       - tree
       - net-tools
       - mc
      state: latest