---
- name: APT. Update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: APT. update && dist-upgrade 
  apt:
    upgrade: dist

- name: APT. Install packages to allow apt to use a repository over HTTPs
  apt:
   name: "{{ item }}"
   state: latest
  loop: "{{ apt_https_install }}"

- name: APT. Install NTP
  apt:
   name: ntp
   state: latest
  notify:
  - NTP. Config service
  - NTP. Enable service

- name: APT. Install additional admin-tools
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ apt_tools_install }}"
  
- name: APT. Autoremove
  apt:
   autoremove: yes
