---
- name: Cache update && Update packeges
  apt:
   upgrade: dist
   update_cache: yes
   cache_valid_time: 3600

- name: Install additional packeges
  apt:
   pkg:
    - bash-completion
    - net-tools
    - tree
    - mc
    - vim
    - git
    - htop
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - apt-transport-https
   state: latest
