---
- name: Check python2 installiation
  stat:
   path: /usr/bin/python2
  register: python2
   
- name: Check python3 installiation
  stat:
   path: /usr/bin/python3
  register: python3

- name: Check python alternatives
  stat:
   path: /etc/alternatives/python
  register: alternative

- name: Install latest python3
  apt:
   name: python3
   state: latest

- block:

  - name: alternative for python2
    alternatives:
     name: python
     path: /usr/bin/python2
     link: /usr/bin/python
     priority: 10

  - name: alternative for python3
    alternatives:
     name: python
     path: /usr/bin/python3
     link: /usr/bin/python
     priority: 20

  when:
   - "not alternative.stat.exists"
   - "python2.stat.exists"
